Update C# FFI
linksplatform/Data.Doublets pull request #270
Opened 2021-12-17 07:28 UTC by FreePhoenix888

- Add `FFI.UnitedMemoryLinks`
- Move converters and constructor to class head
- Update api
- Update csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
- Export rust ffi functions
- Revert rust extert API
- Use C# types for rust extern API
- Use C# types in FFI UnitedMemryLinks fields
- Update UnitedMemoryLinks(string path)
- Update FFI Count(IList<TLink> restrictions)
- Update Count(IList<TLink> restrictions)
- Update FFI Each()
- Update FFI Create()
- Update FFI Update()
- Update FFI Delete()
- Update FFI Dispose()
- Reformat

2021-12-19 14:15 UTC, uselessgoddess requested changes
Look here

2021-12-19 14:15 UTC, uselessgoddess commented on csharp/Platform.Data.Doublets.Benchmarks/MemoryBenchmarks.cs
> +            _ffiUnitedMemory.Dispose();
Wipe up after yourself. This isn't RAII.
```suggestion
            _ffiUnitedMemory.Dispose();
            File.Delete("db.links");
```

2021-12-19 14:15 UTC, uselessgoddess commented on csharp/Platform.Data.Doublets.Tests/GenericLinksTests.cs
> +            }
May be
```suggestion
            using var links = new FFI.UnitedMemoryLinks<TLink>("db.links");
            action(links);
```

2021-12-19 14:15 UTC, uselessgoddess commented on csharp/Platform.Data.Doublets.Tests/ILinksBasicTests.cs
> +
It's a wrong test
Need `Assert.Equal(3U, links.Count())`

2021-12-19 14:15 UTC, uselessgoddess commented on csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
> +        private readonly unsafe void* _body;
May be
```suggestion
        private readonly unsafe void* _ptr;
```

2021-12-19 14:15 UTC, uselessgoddess commented on csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
> +            if (wasDisposed)
Don't shoot yourself in the foot
```suggestion
            if (wasDisposed && _body != null)
```

2021-12-19 21:54 UTC, Konard requested changes

2021-12-19 21:54 UTC, Konard commented on csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
> +    struct FfiLink_Uint8
```suggestion
    struct FfiLink_UInt8
```

2021-12-19 21:54 UTC, Konard commented on csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
> +    struct FfiLink_Uint16
```suggestion
    struct FfiLink_UInt16
```

2021-12-19 21:54 UTC, Konard commented on csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
> +        public static extern byte ByteUnitedMemoryLinks_Update(void* self, byte* restriction, nuint restrictionsLength,  byte* substitution, nuint substitutionLength);
```suggestion
        public static extern byte ByteUnitedMemoryLinks_Update(void* self, byte* restriction, nuint restrictionLength, byte* substitution, nuint substitutionLength);
```

2021-12-19 21:54 UTC, Konard commented on csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
> +        public static extern byte ByteUnitedMemoryLinks_Delete(void* self, byte* restriction, nuint len);
```suggestion
        public static extern byte ByteUnitedMemoryLinks_Delete(void* self, byte* restriction, nuint restrictionLength);
```

2021-12-19 21:54 UTC, Konard commented on csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
> +        public static extern byte ByteUnitedMemoryLinks_Create(void* self);
```suggestion
        public static extern byte ByteUnitedMemoryLinks_Create(void* self, byte* substitution, nuint substitutionLength);
```

2021-12-20 14:30 UTC, uselessgoddess commented on csharp/Platform.Data.Doublets/FFI/UnitedMemoryLinks.cs
> +        public static extern byte ByteUnitedMemoryLinks_Delete(void* self, byte* restriction, nuint len);
🥺

2021-12-21 14:45 UTC, uselessgoddess approved these changes

2022-01-15 16:22 UTC, merged